name:                TowersOfHanoi
version:             0.1.0.0
github:              "githubuser/TowersOfHanoi"
license:             BSD-3-Clause
author:              "Elvis Jose Castro Huanca"
maintainer:          "castro.huanca.elvis@gmail.com"
copyright:           "2024 Elvis Castro"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/TowersOfHanoi#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  TowersOfHanoi-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TowersOfHanoi

tests:
  TowersOfHanoi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TowersOfHanoi
